# Generated by Django 4.2.7 on 2023-11-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200)),
                ('familya', models.CharField(blank=True, max_length=200, null=True)),
                ('mashina_rasm', models.ImageField(upload_to='media')),
                ('hodim_rasm', models.ImageField(blank=True, null=True, upload_to='media')),
                ('tel', models.CharField(max_length=20)),
                ('telegram_link', models.CharField(blank=True, max_length=200, null=True)),
                ('modeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.car_model')),
            ],
        ),
    ]
